name: 🚀 Production Deployment to https://co-IT.eu

on:
  workflow_dispatch:
  push:
    branches: ['main']

env:
  ORIGIN: https://co-IT.eu
  PUBLIC_SEO_EXCLUDED_ROUTES: |
    /kontrakte/
    /cyber/*
    /produkte/passwort-manager/

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v7

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.11.0

      - name: 👷‍♂️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: 💿 Install dependencies
        run: pnpm install

      - name: 🛠️ Build app
        env:
          ORIGIN: ${{ env.ORIGIN }}
        run: pnpm build --prod

      - name: 🎨 Check formatting
        run: pnpm format.check

      - name: 🧹 Lint
        run: pnpm lint

      - name: 🔑 Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🚮 Azure delete old Static Website
        uses: azure/CLI@v1
        with:
          inlineScript: |
            tdnf install azure-cli=2.76.0 -y && \
            az storage blob delete-batch --pattern '*' --account-name coiteu --auth-mode key -s '$web'

      - name: 🚢 Deploy to Azure Static Website
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --overwrite --account-name coiteu --auth-mode key -d '$web' -s './dist'

      - name: 🧹 Azure purge CDN
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az account set --subscription "Productive_Sites"
            az afd endpoint purge --content-paths  "/*" --profile-name "coiteu" --endpoint-name "coiteu" --resource-group "coIteu" --domains "co-it.eu"

      - name: 🚪 Azure logout
        run: |
          az logout
        if: always()
