name: 👩🏻‍💻 Pull Request

on:
  workflow_dispatch:
  pull_request:

env:
  ORIGIN: https://beta.co-IT.eu

jobs:
  check:
    name: 🕵️‍♂️ Check
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v7

      - name: '📦 Setup pnpm'
        uses: pnpm/action-setup@v6
        with:
          version: 11.11.0

      - name: 👷‍♂️ Setup Node.js for use with actions
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: 💿 Clean install dependencies
        run: pnpm install

      - name: 🛠️ Build app
        env:
          ORIGIN: ${{ env.ORIGIN }}
        run: pnpm build --prod

      - name: 🎨 Check formatting
        run: pnpm format.check

      - name: 🧹 Lint
        run: pnpm lint
